AND:&;OR:|;XOR:~=
(l;r):"\n"\'"\n\n"\1:"i.txt"
w:!/``I$'+": "\'l
c:!/+{x(4;1 0 2)}'`$" "\'r
e:{$[^v:w x;(.*a).o'1_a:c x;v]}
2/e'Z@>Z:("z"=*'$:)#!c

c:c@'<'c
f:{c?x@<x}
A:{xor:f`XOR,x,y
   nd:f`AND,x,y
   out:f`XOR,xor,z
   car:f`OR,nd,f`AND,xor,z
   *| \(xor;nd;out;car)}
S:{c[|x]:c x}
S`qdg`z12
S`vvf`z19
S`dck`fgn
S`nvh`z37
/ (f`AND`x00`y00){A. y,x}/1_+2 0N#!w

`0:","/${x@<x}`qdg`z12`vvf`z19`dck`fgn`nvh`z37
